config/routes.rb
Rails.application.routes.draw do
  resources :meals
  resources :orders, only: [:update, :destroy]

  post 'orders/attribute' => 'orders#attribute'
  post 'orders/construct' => 'orders#construct'

  post 'meals/:id/closeorders' => 'meals#close_orders'
  get 'meals/:id/orders' => 'meals#orders'

  get 'welcome/index'

  devise_for :users

  root 'welcome#index'

end

app/models/meal.rb
# encoding: utf-8
class Meal < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_many :orders
  belongs_to :owner, class_name: 'User', foreign_key: 'owner_id'

  def total_cost
    total = 0.0
    orders.each do |o|
      total += o.cost
    end
    return total
  end

  def total_owing
    owing = 0.0
    orders.each do |o|
      owing += o.cost unless o.has_paid?
    end
    return owing
  end

  def close_orders
    transaction do
      self.orders_closed = true
      orders.each do |o|
        if o.empty?
          orders.delete(o)
        end
      end
    end
    generate_summary!
    save()
  end

  def generate_summary!
    same_orders = {}
    orders.each do |o|
      next if o.description.blank?
      key = o.description.downcase
      same_orders[key] ||= {:actual => nil, :count => 0}
      same_orders[key][:count] += 1
      same_orders[key][:actual] ||= o.description
    end
    self.summary = ''
    same_orders.keys.sort.each do |k|
      self.summary += "#{same_orders[k][:actual]} ✕#{same_orders[k][:count]}\n"
    end
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :meal
  belongs_to :user

  def empty?
    cost == 0 && description.blank?
  end

  def initialize(params)
    super(params)
    self.cost ||= 0.0
  end

  def update(params)
    params[:cost] = 0.0 if params[:cost] == ''
    super(params)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :meals
  has_many :orders

  after_create :add_orders

  private
  def add_orders
    Meal.where(orders_closed: nil).each do |m|
      m.users << self
      m.orders.create(:user => self, :meal => m)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    '/'
  end

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) << :payment_details
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :set_meal, only: [:show, :edit, :update, :destroy, :close_orders, :orders]

  def new
    @users = User.where(is_deleted: false).order(email: :asc).all
    @meal = Meal.new do |m|
      m.users = @users
    end
  end

  def create
    @meal = Meal.new(meal_params)
    @meal.users.each do |user|
      @meal.orders << Order.new(:user_id => user.id, :meal_id => @meal.id)
    end
    check_owner
    if @meal.save
      url = "#{request.protocol}#{request.host_with_port}#{meal_path(@meal)}"
      MealMailer.creation_email(@meal, url).deliver
      redirect_to @meal
    else
      render 'new'
    end
  end

  def edit
    @users = User.all
  end

  def index
    @meals = Meal.all.sort_by { |m| m.date }.reverse
  end

  def show
  end

  def update
    @meal.transaction do
      if @meal.update(meal_params)
        unless @meal.orders_closed?
          @meal.users.each do |u|
            if Order.where('user_id = ? AND meal_id = ?', u.id, @meal.id).empty?
              @meal.orders.create(:user => u)
            end
          end
        end
        check_owner
        flash[:notice] = 'Meal successfully saved'
      else
        flash[:alert] = "Meal couldn't be saved"
      end
    end
    redirect_to @meal
  end

  def destroy
    if @meal.destroy
      render :nothing => true, :status => 200
      flash[:notice] = 'Meal successfully deleted'
    end
  end

  def close_orders
    @meal.close_orders
    unless @meal.owner.payment_details.blank?
      #@meal.orders.each do |order|
      #  MealMailer.orders_closed_email(@meal, order).deliver
      #end
    end
    flash[:notice] = "Orders closed for #{@meal.title}!"
    render :nothing => true, status => :ok
  end

  def orders
    render :partial => 'orders/order_table', status => :ok
  end

  private
  def check_owner
    @meal.owner_id = current_user.id if @meal.users.none? { |u| u.id == @meal.owner_id }
  end

  def set_meal
    @meal = Meal.find(params[:id])
  end

  def meal_params
    params.require(:meal).permit(:title, :date, :website, :owner_id, :user_ids => [], :order_ids => [])
  end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController

  before_action :set_order, only: [:update, :attribute]

  def update
    if @order.meal.orders_closed?
      flash[:alert] = 'Meal has been closed'
    elsif @order.update(order_params)
      flash[:notice] = 'Order placed!'
    end
    redirect_to @order.meal
  end

  def attribute
    @order.send(params[:attribute]+'=', params[:value])
    @order.save()
    render :nothing => true, status: :ok
  end

  private
  def set_order
    @order = Order.find(params[:id])
  end

  def attr_params
    params.permit(:id, :attribute, :value)
  end

  def permitted_attributes
    [:description, :cost, :has_paid]
  end

  def order_params
    params.require(:order).permit(permitted_attributes)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :set_order, only: [:update, :attribute, :destroy]

  def construct
    sanitised_params = create_params
    @order = Order.create(meal_id: sanitised_params[:meal_id], user_id: sanitised_params[:user_id])
    render :partial => 'order_form', status => :created
  end

  def update
    if @order.meal.orders_closed?
      flash[:alert] = 'Meal has been closed'
    elsif @order.update(order_params)
      flash[:notice] = 'Order placed!'
    end
    redirect_to @order.meal
  end

  def destroy
    @order.delete()
    render :nothing => true, status: :ok
  end

  def attribute
    @order.send(params[:attribute]+'=', params[:value])
    @order.save()
    render :nothing => true, status: :ok
  end

  private
  def set_order
    @order = Order.find(params[:id])
  end

  def attr_params
    params.permit(:id, :attribute, :value)
  end

  def permitted_attributes
    [:description, :cost, :has_paid]
  end

  def create_params
    params.permit(:user_id, :meal_id)
  end

  def order_params
    params.require(:order).permit(permitted_attributes)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  skip_before_action :authenticate_user!
  
  def index
    if user_signed_in?
      redirect_to(meals_path)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
  #stuffs for devise, such that I can render a partial view
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EnableFood</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="title" class="nav-bar-div">
  <a href="/"><%= image_tag('EnableFood_MainLogo.png', :class => 'nav-bar-logo') %></a>
  <p class="navbar-text pull-right">
    <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
        <%= link_to 'Sign up', new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to 'Login', new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
  </p>
</div>

<% if notice %>
    <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
<% end %>

<div id="body">
<%= yield %>
</div>

</body>
</html>

app/views/layouts/meal_mailer.html.erb
<!DOCTYPE html>
<html>
  <head>
      <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
      <style>
      a { text-decoration: none; color:#00B8E4; }
      a:visited { color: #00B8E4; }
      a:hover { text-decoration: underline; }
      </style>
   </head>
   <body style="width: 600px; padding: 20px; background-color: #d5e7f4; font-family: 'Helvetica Neue', Helvetica, Arial, Sans-Serif;color: #4c5257;">
        <span style="display:block; background:linear-gradient(white,#BFC2C6);height:40px;width:100%;top:0;min-width:600px;">
        <span style="font-size: 40px; font-weight: bold;margin-right:-8px;">Enable</span>
        <span style="font-size: 40px; color: #00B8E4;">Food</span>
        </span>

        <%= yield %>

    </body>
</html>

app/views/meals/_meal.html.erb
<br/>
<% is_owner = (@meal.owner == current_user) %>
<% if is_owner %>
    <%= link_to 'Edit', edit_meal_path(@meal), :class => 'button' %>
<% else %>
    <div id="owner">
        <p>Meal being run by: <br /> <%= @meal.owner.email %></p>
        <span>
        Payment details: <br/><%= simple_format(@meal.owner.payment_details) %>
        </span>
    </div>
<% end %>
<div class="right"><h3> <%= @meal.date %> </h3></div>
<h2 class="title"> <%= @meal.title %> </h2>
<%= image_tag('menu_swirl.png', :class => 'center') %>

<div id="meal_id" data-meal-id="<%=@meal.id%>"></div>
<p>
  <%= link_to @meal.website, @meal.website, :target => '_blank' %>
</p>
<div class="orders_container">
  <% @meal.orders.all.where(user_id: current_user.id).each do |order| %>
    <% if !order.nil? && !@meal.orders_closed %>
       <% @order = order %>
       <%= render('orders/order_form') %>
    <% end %>
  <% end %>
</div>
<div>
  <%= render('orders/order_table', :locals => { :owner => is_owner, :meal => @meal }) %>
  <% if is_owner && !@meal.orders_closed %>
    <div class="right-ish">
        <div class="button right close-orders" > Close Orders </div>
    </div>
  <% end %>
  <% if @meal.orders_closed? && !@meal.summary.nil?  %>
      <p class="center"><%= @meal.summary.gsub("\n", '<br />').html_safe %> </p>
  <% end %>
</div>

app/views/meals/_meal_form.html.erb
<%= form_for @meal do |f| %>
    <% if @meal.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@meal.errors.count, "error") %> prohibited this meal from being saved:</h2>
          <ul>
            <% @meal.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <% @meal.orders.each do |order| %>
        <%= f.hidden_field :order_ids, :multiple => true, :value => order.id %>
    <% end %>
    <p>
      <%= f.text_field :title, size: 50, placeholder: 'Enter tagline / description here' %>
    </p>

    <p>
      <%= f.label :date %>
      <%= f.date_select :date %>
    </p>

    <p>
      <%= f.text_field :website, size: 50, placeholder: 'Enter menu website here' %>
    </p>

    <p>
      <%= f.label 'Owner' %>
      <%= f.collection_select(:owner_id, @users, :id, :email, {:selected => current_user.id}) %>
    </p>
    <p>
        <%= f.label 'Users to include' %>
      <div class="field">
        <%= f.collection_check_boxes(:user_ids, @users, :id, :email) do |b| %>
          <%= b.label('data-value' => b.value) { b.check_box + b.text } %>
            <br/>
        <% end %>
      </div>
    </p>
    <p>
      <%= f.submit 'Save' %>
      <% if @meal.id.nil? %>
          <%= link_to 'Cancel', meals_path, class: 'button' %>
      <% else %>
        <%= link_to 'Cancel', meal_path, class: 'button' %>
      <% end %>
    </p>
<% end %>

app/views/meals/edit.html.erb
<h3>Edit Meal</h3>
<%= render('meal_form', method: :patch) %>

app/views/meals/index.html.erb
<h1>Meals</h1>

<%= link_to('Create New', new_meal_path, class: 'button') %>
<table class="table">
  <thead>
      <tr>
        <th style="width: 20%;"></th>
        <th style="width: 20%;">Date</th>
        <th>Title</th>
      </tr>
  </thead>
  <tbody>
      <% @meals.each do |meal| %>
          <tr class="list-item" onclick="meal.show_meal(event, <%= meal.id %>);" >
            <td>
              <% if meal.owner_id == current_user.id %>
                <div onclick="meal.delete_meal(event, <%= meal.id %>);" class="button">Delete</div>
              <% end %>
            </td>
            <td><%= meal.date %></td>
            <td><%= meal.title %></td>
          </tr>
      <% end %>
  </tbody>
</table>

app/views/meals/new.html.erb
<h3>Create a new Meal</h3>
<%= render('meal_form') %>

app/views/meals/show.html.erb
<%= render('meal') %>

app/views/order/_order_table.html.erb
<div id="orders">
    <table class="center orders-table">
      <thead>
      <tr><th colspan="3">Orders:</th><th></th><th></th></tr>
      </thead>
      <tbody>
      <% @meal.orders.each do |o| %>
          <% @order = o %>
          <%= render :partial => 'order/order', :locals => { :owner => @meal.owner_id == current_user.id } %>
      <% end %>
      </tbody>
      <tfoot>
      <tr><td class="total-row" colspan="3">Total: <%= number_to_currency @meal.total_cost %></td></tr>
      <tr><td class="total-row" colspan="3">Owing: <%= number_to_currency @meal.total_owing %></td></tr>
      </tfoot>
    </table>
</div>

app/views/orders/_order.html.erb
<tr class="<%= 'disabled-row' if @order.has_paid? %>" >
  <td><%= @order.user.email %></td>
  <td><%= @order.description %></td>
  <td style="text-align: right"><%= number_to_currency @order.cost %></td>
  <% if owner %>
      <td class="no-wrap">
        <label>
          <input class="ajax-paid" type="checkbox" value="<%= @order.id %>"
                 <%= 'checked="checked"' if @order.has_paid? %> >Paid?</label>
      </td>
  <% end %>
</tr>

app/views/orders/_order_form.html.erb
<%= form_for @order do |f| %>
    <div class="center no-wrap">
        <a href="#" class="delete_order" data-order-id="<%= @order.id %>">[-]</a>
        <%= f.label 'Your Order:' %>
        <%= f.text_field :description, size: 50, placeholder: 'desired item' %>
        <%= f.label '$' %>
        <%= f.text_field :cost, size:15, placeholder: 'price', :value => number_with_precision(f.object.cost, :precision => 2) %>
        <%= f.submit 'Update Order!' %>
        <a href="#" class="new_order" data-user-id="<%= @order.user_id %>" data-meal-id="<%= @order.meal_id %>">[+]</a>
    </div>
<% end %>
<div class="spacer"></div>

app/views/orders/_order_table.html.erb
<div id="orders">
    <table class="center orders-table">
      <thead>
      <tr><th colspan="3">Orders:</th><th></th><th></th></tr>
      </thead>
      <tbody>
      <% @meal.orders.each do |o| %>
          <% @order = o %>
          <%= render :partial => 'orders/order', :locals => { :owner => @meal.owner_id == current_user.id } %>
      <% end %>
      </tbody>
      <tfoot>
      <tr><td class="total-row" colspan="3">Total: <%= number_to_currency @meal.total_cost %></td></tr>
      <tr><td class="total-row" colspan="3">Owing: <%= number_to_currency @meal.total_owing %></td></tr>
      </tfoot>
    </table>
</div>

app/views/welcome/index.html.erb
<p>This is a web app for figuring out who wants what, who has paid and which thieving bastards still owe money.</p>

<% if !user_signed_in? %>
    <%= render 'devise/sessions/form' %>
<% end %>